// All 24 pubs on the Reading Ale Trail 2026
// Coordinates sourced from OpenStreetMap/Nominatim

export interface Pub {
  id: number;
  name: string;
  area: string;
  address: string;
  lat: number;
  lng: number;
  isBookletSeller: boolean;
}

export const pubs: Pub[] = [
  {
    id: 1,
    name: "Nags Head",
    area: "Reading",
    address: "5 Russell Street, Reading, RG1 7XD",
    lat: 51.4546,
    lng: -0.9822,
    isBookletSeller: true,
  },
  {
    id: 2,
    name: "Alehouse",
    area: "Reading",
    address: "2 Broad Street, Reading, RG1 2BH",
    lat: 51.4552,
    lng: -0.9702,
    isBookletSeller: true,
  },
  {
    id: 3,
    name: "Retreat",
    area: "Reading",
    address: "8 St John's Street, Reading, RG1 4EH",
    lat: 51.4533,
    lng: -0.9606,
    isBookletSeller: true,
  },
  {
    id: 4,
    name: "Crown",
    area: "Caversham",
    address: "Promenade Road, Caversham, Reading, RG4 8AA",
    lat: 51.4666,
    lng: -0.9767,
    isBookletSeller: false,
  },
  {
    id: 5,
    name: "Greyfriar",
    area: "Reading",
    address: "53 Greyfriars Road, Reading, RG1 1PA",
    lat: 51.4587,
    lng: -0.9756,
    isBookletSeller: false,
  },
  {
    id: 6,
    name: "Castle Tap",
    area: "Reading",
    address: "120 Castle Street, Reading, RG1 7RJ",
    lat: 51.4519,
    lng: -0.979,
    isBookletSeller: false,
  },
  {
    id: 7,
    name: "Rising Sun",
    area: "Reading",
    address: "16 Castle Street, Reading, RG1 7RD",
    lat: 51.4537,
    lng: -0.975,
    isBookletSeller: false,
  },
  {
    id: 8,
    name: "Farriers Arms",
    area: "Spencers Wood",
    address: "Basingstoke Road, Spencers Wood, RG7 1AE",
    lat: 51.3952,
    lng: -0.9734,
    isBookletSeller: false,
  },
  {
    id: 9,
    name: "Railway Tavern",
    area: "Reading",
    address: "31 Greyfriars Road, Reading, RG1 1PA",
    lat: 51.4581,
    lng: -0.9758,
    isBookletSeller: false,
  },
  {
    id: 10,
    name: "Fox & Hounds",
    area: "Tilehurst",
    address: "City Road, Tilehurst, Reading, RG31 5SB",
    lat: 51.4521,
    lng: -1.0541,
    isBookletSeller: false,
  },
  {
    id: 11,
    name: "Fox & Hounds",
    area: "Sheffield Bottom",
    address: "Deans Copse Road, Sheffield Bottom, RG7 4BE",
    lat: 51.4241,
    lng: -1.0677,
    isBookletSeller: false,
  },
  {
    id: 12,
    name: "Lyndhurst",
    area: "Reading",
    address: "88 Queens Road, Reading, RG1 4DG",
    lat: 51.4536,
    lng: -0.9615,
    isBookletSeller: false,
  },
  {
    id: 13,
    name: "Park House",
    area: "Reading",
    address: "Whiteknights Campus, Reading, RG6 6UR",
    lat: 51.4401,
    lng: -0.9432,
    isBookletSeller: false,
  },
  {
    id: 14,
    name: "Foresters Arms",
    area: "Reading",
    address: "79-81 Brunswick Street, Reading, RG1 6NY",
    lat: 51.4506,
    lng: -0.9894,
    isBookletSeller: false,
  },
  {
    id: 15,
    name: "Royal Oak",
    area: "Tilehurst",
    address: "Westwood Glen, The Triangle, Tilehurst, RG31 5NW",
    lat: 51.4611,
    lng: -1.0489,
    isBookletSeller: false,
  },
  {
    id: 16,
    name: "Six Bells",
    area: "Burghfield",
    address: "The Hatch, Burghfield, RG30 3TH",
    lat: 51.4113,
    lng: -1.0418,
    isBookletSeller: false,
  },
  {
    id: 17,
    name: "Elm Tree",
    area: "Beech Hill",
    address: "Beech Hill Road, Beech Hill, RG7 2AS",
    lat: 51.3717,
    lng: -1.0032,
    isBookletSeller: false,
  },
  {
    id: 18,
    name: "Bull Inn",
    area: "Sonning",
    address: "High Street, Sonning, RG4 6UP",
    lat: 51.4736,
    lng: -0.9116,
    isBookletSeller: false,
  },
  {
    id: 19,
    name: "The Bull Inn",
    area: "Arborfield Cross",
    address: "Swallowfield Road, Arborfield, RG2 9QD",
    lat: 51.3976,
    lng: -0.9071,
    isBookletSeller: false,
  },
  {
    id: 20,
    name: "The Swan",
    area: "Pangbourne",
    address: "Shooter's Hill, Pangbourne, RG8 7DU",
    lat: 51.4861,
    lng: -1.0902,
    isBookletSeller: false,
  },
  {
    id: 21,
    name: "Bell",
    area: "Waltham St Lawrence",
    address: "The Street, Waltham St Lawrence, RG10 0JJ",
    lat: 51.4851,
    lng: -0.8065,
    isBookletSeller: false,
  },
  {
    id: 22,
    name: "Castle Inn",
    area: "Hurst",
    address: "Church Hill, Hurst, RG10 0SJ",
    lat: 51.4502,
    lng: -0.8566,
    isBookletSeller: false,
  },
  {
    id: 23,
    name: "The Flowing Spring",
    area: "Playhatch",
    address: "Henley Road, Playhatch, RG4 9RB",
    lat: 51.4847,
    lng: -0.9263,
    isBookletSeller: false,
  },
  {
    id: 24,
    name: "The Sun",
    area: "Whitchurch Hill",
    address: "Hill Bottom, Whitchurch Hill, RG8 7PU",
    lat: 51.5088,
    lng: -1.0738,
    isBookletSeller: false,
  },
];
